version: 2.1
workflows:
  build:
    jobs:
      - build
      - package_and_upload:
          requires:
            - build
    
executors:
  build-executor:
    docker:
      - image: cimg/node:12.10.0
    working_directory: /test
  upload-executor: aws-ecr/default
    
orbs:
  aws-ecr: enokawa/aws-ecr@0.0.2
  
jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
          
  package_and_upload:
    executor: upload-executor
    steps:
      - attach_workspace:
          at:  .
      - run:
          name: Creating Docker Image From Dockerfile
          command: |
            echo 'export TAG=${CIRCLE_PIPELINE_NUM}' >> ${BASH_ENV}
            echo 'export IMAGE_NAME=438413248147.dkr.ecr.us-east-1.amazonaws.com/counter' >> ${BASH_ENV}
            source ${BASH_ENV}
            docker build -t ${IMAGE_NAME}:${TAG} .
      - run:
          name: Listing docker images
          command: docker images
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: "counter"
          tag: "${CIRCLE_PIPELINE_NUM}"
      - run:
          name: Listing docker images
          command: docker images
