version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@2.2.1
  
workflows:
  build_and_push_image:
    jobs:
      - aws-ecs/deploy-service-update:
          aws-region: AWS_REGION
          cluster-name: 'counter-development-cluster'
          container-image-name-updates: 'container=counter-task,tag=v1.0.0'
          family: 'counter-task'
          requires:
            - aws-ecr/build-and-push-image
