version: 2.1

workflows:
  build:
    jobs:
      - build
      - package_and_upload:
          requires:
            - build
 
orbs:
  aws-ecr: enokawa/aws-ecr@0.0.2

executors:
  build-executor:
    docker:
      - image: cimg/node:12.10.0
    working_directory: /test
  upload-executor: aws-ecr/default
  
jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .


  package_and_upload:
    executor: upload-executor
    steps:
      - attach_workspace:
          at:  .
      - aws-ecr/ecr-login
      - run:
          name: Build and push Docker image to ECR
          command: |
            echo 'export TAG=${TAG}' >> ${BASH_ENV}
            echo 'export IMAGE_NAME=438413248147.dkr.ecr.us-east-1.amazonaws.com/counter' >> ${BASH_ENV}
            source ${BASH_ENV}
            docker build ${IMAGE_NAME}:${TAG} .
            docker push ${IMAGE_NAME}:${TAG}
