version: 2.1
workflows:
  build:
    jobs:
      - build
      - package:
          requires:
            - build
    
executors:
  job-executor:
    docker:
      - image: cimg/node:12.11.0
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  
    working_directory: /tmp
    
jobs:
  build:
    executor: job-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
#       - persist_to_workspace:
#           root: /tmp
#           paths:
#             - "*"
          
  package:
    executor: job-executor
    steps:
#       - attach_workspace:
#           at: /tmp
      - run: ls -latrh
#       - run:
#           name: Creating Docker Image From Dockerfile
#           command: docker build -t counter:v1 .
#       - run:
#           name: Listing docker images
#           command: docker images
