version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  
workflows:
  build:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          region: us-east-1
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: counter
          tag: v1.1.2
          requires:
            - build


executors:
  test-executor:
    docker:
      - image: cimg/node:12.10.0
  
jobs:
  test:
    executor: test-executor
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm run test
