version: 2.1
    
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-cli-version: latest
          context: myContext
          create-repo: false
          dockerfile: Dockerfile
          executor: aws-ecr/default
          push-image: true
          repo: counter
          skip-when-tags-exist: true
          tag: 'v1.0.2'
            
