version: 2.1
workflows:
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/node:12.11.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - run: 
          name: Testing build
          command: ls -latrh
      - run:
          name: Creating Docker Image From Dockerfile
          command: docker build -t counter:v1 .
      - run:
          name: Listing docker images
          command: docker images
    
  
