version: 2.1
workflows:
  build:
    jobs:
      - build
      - package_and_upload:
          requires:
            - build
    
executors:
  job-executor:
    docker:
      - image: cimg/node:12.11.0
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD
    working_directory: /test
    
orbs:
  aws-ecr: enokawa/aws-ecr@0.0.2
  
jobs:
  build:
    executor: job-executor
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
          
  package_and_upload:
    executor: job-executor
    steps:
      - attach_workspace:
          at:  .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Creating Docker Image From Dockerfile
          command: |
            echo 'export TAG=${CIRCLE_BUILD_NUM}' >> ${BASH_ENV}
            echo 'export IMAGE_NAME=438413248147.dkr.ecr.us-east-1.amazonaws.com/counter' >> ${BASH_ENV}
            source ${BASH_ENV}
            docker build -t ${IMAGE_NAME}:${TAG} .
      - run:
          name: Listing docker images
          command: docker images
      - aws-ecr/ecr-login:
      - aws-ecr/push-image:
          repo: "counter"
          tag: "${CIRCLE_BUILD_NUM}"
      - run: docker images
#       - run:
#           name: Uploading image to ECR
#           command: |
          
